# Generated by Django 6.0.3 on 2026-03-20 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu_de_l_affirmation', models.TextField()),
                ('type_affirmation', models.CharField(choices=[('thèse', 'Thèse'), ('convention', 'Convention'), ('renvoi', 'Renvoi'), ('mise_en_garde', 'Mise en garde')], max_length=50)),
                ('à_ne_pas_contredire', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'affirmations_posées',
            },
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField(unique=True)),
                ('titre', models.CharField(max_length=500)),
                ('rôle_du_chapitre', models.TextField(choices=[('introduction', 'Introduction'), ('développement', 'Développement'), ('conclusion', 'Conclusion')], default='développement')),
                ('périmètre_thématique', models.TextField()),
                ('exclusions_thématiques', models.TextField()),
                ('justification_indépendance_chapitre', models.TextField()),
                ('statut', models.CharField(choices=[('à_rédiger', 'À rédiger'), ('en_cours', 'En cours'), ('rédigé', 'Rédigé'), ('validé', 'Validé')], default='à_rédiger', max_length=50)),
            ],
            options={
                'db_table': 'chapitres',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField()),
                ('titre', models.CharField(max_length=500)),
                ('objectif_pédagogique', models.TextField()),
                ('périmètre_thématique', models.TextField()),
                ('exclusions_thématiques', models.TextField()),
                ('message_clé_à_retenir', models.TextField()),
                ('angle_rhétorique', models.TextField(blank=True, null=True)),
                ('texte_rédigé', models.TextField(blank=True, null=True)),
                ('nombre_de_mots_cible', models.IntegerField(blank=True, null=True)),
                ('nombre_de_mots_rédigés', models.IntegerField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('à_rédiger', 'À rédiger'), ('en_cours', 'En cours'), ('rédigé', 'Rédigé'), ('validé', 'Validé')], default='à_rédiger', max_length=50)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stage.chapitre')),
            ],
            options={
                'db_table': 'sections',
                'unique_together': {('chapitre', 'ordre')},
            },
        ),
        migrations.CreateModel(
            name='Exemple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_de_l_exemple', models.TextField()),
                ('description_complète_de_l_exemple', models.TextField()),
                ('chiffres_ou_données_utilisés', models.TextField(blank=True, null=True)),
                ('source_ou_origine', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exemples',
            },
        ),
        migrations.CreateModel(
            name='FicheStrategique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet_précis', models.TextField()),
                ('cible', models.TextField()),
                ('niveau', models.CharField(max_length=100)),
                ('objectif_lecteur', models.TextField()),
                ('logique_ordre_des_chapitres', models.TextField(default='chronologique')),
                ('sujets_exclus_du_livre', models.TextField(blank=True, null=True)),
                ('contraintes_éditoriales', models.TextField(blank=True, null=True)),
                ('fiche_validée_par_humain', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'fiche_strategique',
            },
        ),
        migrations.CreateModel(
            name='Glossaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terme', models.CharField(max_length=255, unique=True)),
                ('définition_utilisée_dans_ce_livre', models.TextField()),
                ('mise_en_garde_sur_ce_terme', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'glossaire',
            },
        ),
        migrations.CreateModel(
            name='ProcessStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('is_done', models.BooleanField(default=False)),
                ('redirect_url', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ErreurFrequente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu_de_l_erreur', models.TextField()),
                ('placée', models.BooleanField(default=False)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Stage.section')),
            ],
            options={
                'db_table': 'erreurs_frequentes',
            },
        ),
        migrations.CreateModel(
            name='EtapeEssentielle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu_de_l_etapes', models.TextField()),
                ('placée', models.BooleanField(default=False)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Stage.section')),
            ],
            options={
                'db_table': 'etapes_essentielles',
            },
        ),
        migrations.CreateModel(
            name='IdeeRecherchee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu_de_l_idée', models.TextField()),
                ('placée', models.BooleanField(default=False)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Stage.section')),
            ],
            options={
                'db_table': 'idees_recherchees',
            },
        ),
        migrations.CreateModel(
            name='NotionIndispensable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_de_la_notion', models.TextField()),
                ('contenu_de_la_notion', models.TextField()),
                ('placée', models.BooleanField(default=False)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Stage.section')),
            ],
            options={
                'db_table': 'notions_indispensables',
            },
        ),
        migrations.CreateModel(
            name='Risque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu_du_risque', models.TextField()),
                ('placée', models.BooleanField(default=False)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Stage.section')),
            ],
            options={
                'db_table': 'risque',
            },
        ),
        migrations.CreateModel(
            name='ContenuSection',
            fields=[
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Stage.section')),
                ('contenu', models.TextField(blank=True, null=True)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stage.chapitre')),
            ],
            options={
                'db_table': 'contenu_sections',
            },
        ),
    ]
