# Generated by Django 6.0.3 on 2026-03-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstatus',
            name='sujet_precis',
            field=models.TextField(blank=True),
        ),
    ]
