# Generated by Django 6.0.3 on 2026-04-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stage', '0002_processstatus_sujet_precis'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheCadrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.TextField(blank=True, null=True)),
                ('sommaire', models.TextField(blank=True, null=True)),
                ('hors_perimetre', models.TextField(blank=True, null=True)),
                ('cible', models.TextField(blank=True, null=True)),
                ('niveau', models.TextField(blank=True, null=True)),
                ('objectif_lecteur', models.TextField(blank=True, null=True)),
                ('nb_chapitre', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
