# Generated by Django 6.0.3 on 2026-04-02 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stage', '0003_fichecadrage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notionindispensable',
            name='nom_de_la_notion',
        ),
    ]
