# Generated by Django 6.0.3 on 2026-04-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stage', '0004_remove_notionindispensable_nom_de_la_notion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapitreDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('titre', models.CharField(blank=True, max_length=255, null=True)),
                ('traite', models.TextField(blank=True, null=True)),
                ('ne_traite_pas', models.TextField(blank=True, null=True)),
                ('pourquoi_distinct', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ChapitreDetails',
            },
        ),
        migrations.CreateModel(
            name='Conclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synthese', models.TextField(blank=True, null=True)),
                ('logique_ensemble', models.TextField(blank=True, null=True)),
                ('prochaines_etapes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Conclusion',
            },
        ),
        migrations.CreateModel(
            name='FilRouge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnage', models.TextField(blank=True, null=True)),
                ('situation_depart', models.TextField(blank=True, null=True)),
                ('evolution', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'FilRouge',
            },
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contexte', models.TextField(blank=True, null=True)),
                ('importance', models.TextField(blank=True, null=True)),
                ('adresse_a', models.TextField(blank=True, null=True)),
                ('organisation', models.TextField(blank=True, null=True)),
                ('promesse', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Introduction',
            },
        ),
        migrations.AlterModelTable(
            name='fichecadrage',
            table='FicheCadrage',
        ),
        migrations.AlterModelTable(
            name='processstatus',
            table='ProcessStatus',
        ),
    ]
