# Generated by Django 6.0.3 on 2026-04-07 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stage', '0005_chapitredetails_conclusion_filrouge_introduction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionDetaillee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('titre_section', models.CharField(blank=True, max_length=255, null=True)),
                ('objectif', models.TextField(blank=True, null=True)),
                ('concept_cle', models.TextField(blank=True, null=True)),
                ('exemple', models.TextField(blank=True, null=True)),
                ('limite', models.TextField(blank=True, null=True)),
                ('mots_cible', models.CharField(blank=True, max_length=50, null=True)),
                ('chapitre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='Stage.chapitredetails')),
            ],
            options={
                'db_table': 'SectionDetaillee',
                'ordering': ['numero'],
            },
        ),
    ]
