# Generated by Django 6.0.3 on 2026-04-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stage', '0006_sectiondetaillee'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroductionTexte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'IntroductionTexte',
            },
        ),
    ]
