# Generated by Django 6.0.3 on 2026-04-09 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stage', '0007_introductiontexte'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenuSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapitre_numero', models.IntegerField(blank=True, null=True)),
                ('section_numero', models.IntegerField(blank=True, null=True)),
                ('titre', models.TextField(blank=True, null=True)),
                ('contenu', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ContenuSections',
            },
        ),
        migrations.CreateModel(
            name='SectionTexte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapitre', models.IntegerField(blank=True, null=True)),
                ('section', models.IntegerField(blank=True, null=True)),
                ('contenu', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SectionTexte',
            },
        ),
        migrations.CreateModel(
            name='FicheSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapitre_numero', models.IntegerField(blank=True, null=True)),
                ('section_numero', models.IntegerField(blank=True, null=True)),
                ('these_centrale', models.TextField(blank=True, null=True)),
                ('arguments_cles', models.JSONField(blank=True, null=True)),
                ('concepts_introduits', models.JSONField(blank=True, null=True)),
                ('a_ne_pas_repeter', models.JSONField(blank=True, null=True)),
                ('liens_chapitres', models.TextField(blank=True, null=True)),
                ('ton_angle', models.TextField(blank=True, null=True)),
                ('raw', models.TextField(blank=True, null=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiches', to='Stage.sectiondetaillee')),
            ],
            options={
                'db_table': 'FicheSection',
            },
        ),
        migrations.CreateModel(
            name='ResumeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapitre_numero', models.IntegerField(blank=True, null=True)),
                ('section_numero', models.IntegerField(blank=True, null=True)),
                ('resume', models.TextField(blank=True, null=True)),
                ('section', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='Stage.sectiondetaillee')),
            ],
            options={
                'db_table': 'ResumeSection',
            },
        ),
    ]
