# Generated by Django 6.0.3 on 2026-04-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stage', '0008_contenusections_sectiontexte_fichesection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConclusionTexte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conclusion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ConclusionTexte',
            },
        ),
    ]
