# Generated by Django 6.0.3 on 2026-04-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stage', '0009_conclusiontexte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_chapitre', models.IntegerField(blank=True, null=True)),
                ('nb_mots_cible', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Variables',
            },
        ),
    ]
