# Generated by Django 6.0.3 on 2026-05-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stage', '0010_variables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.BooleanField(default=False)),
                ('fiche_cadrage', models.BooleanField(default=False)),
                ('recherche', models.BooleanField(default=False)),
                ('plan', models.BooleanField(default=False)),
                ('structure', models.BooleanField(default=False)),
                ('introduction', models.BooleanField(default=False)),
                ('contenu', models.BooleanField(default=False)),
                ('conclusion', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Etapes',
            },
        ),
    ]
