# Generated by Django 6.0.3 on 2026-05-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stage', '0011_etapes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livre_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('livre_titre', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'Livre',
            },
        ),
        migrations.AddField(
            model_name='affirmation',
            name='livre_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapitre',
            name='livre_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapitredetails',
            name='livre_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conclusion',
            name='livre_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conclusiontexte',
            name='livre_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contenusection',
            name='livre_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contenusections',
            name='livre_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erreurfrequente',
            name='livre_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etapeessentielle',
            name='livre_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etapes',
            name='livre_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exemple',
            name='livre_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichecadrage',
            name='livre_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichesection',
            name='livre_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichestrategique',
            name='livre_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filrouge',
            name='livre_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='glossaire',
            name='livre_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ideerecherchee',
            name='livre_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='introduction',
            name='livre_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='introductiontexte',
            name='livre_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notionindispensable',
            name='livre_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumesection',
            name='livre_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risque',
            name='livre_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='livre_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectiondetaillee',
            name='livre_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectiontexte',
            name='livre_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variables',
            name='livre_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
