# Generated by Django 6.0.3 on 2026-06-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stage', '0012_livre_affirmation_livre_id_chapitre_livre_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstatus',
            name='livre_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
