# Generated by Django 6.0.3 on 2026-06-02 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stage', '0013_processstatus_livre_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processstatus',
            name='livre_id',
        ),
    ]
