# Generated by Django 6.0.3 on 2026-06-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stage', '0014_remove_processstatus_livre_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichecadrage',
            name='sommaire',
        ),
        migrations.AddField(
            model_name='fichecadrage',
            name='contraintes_specifiques',
            field=models.TextField(blank=True, null=True),
        ),
    ]
