# Generated by Django 6.0.3 on 2026-06-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stage', '0015_remove_fichecadrage_sommaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilRougeInsertion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapitre_numero', models.IntegerField(blank=True, null=True)),
                ('section_numero', models.IntegerField(blank=True, null=True)),
                ('contenu', models.TextField(blank=True, null=True)),
                ('livre_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'FilRougeInsertion',
                'unique_together': {('chapitre_numero', 'section_numero', 'livre_id')},
            },
        ),
        migrations.CreateModel(
            name='SectionTexteEnrichi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapitre', models.IntegerField(blank=True, null=True)),
                ('section', models.IntegerField(blank=True, null=True)),
                ('contenu', models.TextField(blank=True, null=True)),
                ('livre_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SectionTexteEnrichi',
                'unique_together': {('chapitre', 'section', 'livre_id')},
            },
        ),
    ]
