# Generated by Django 6.0.3 on 2026-06-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stage', '0016_filrougeinsertion_sectiontexteenrichi'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSearchIdee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(blank=True, null=True)),
                ('livre_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'WebSearchIdee',
            },
        ),
        migrations.CreateModel(
            name='WebSearchSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.TextField(blank=True, null=True)),
                ('notions_indispensables', models.JSONField(blank=True, null=True)),
                ('erreurs_frequentes', models.JSONField(blank=True, null=True)),
                ('etapes_essentielles', models.JSONField(blank=True, null=True)),
                ('risque', models.JSONField(blank=True, null=True)),
                ('livre_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'WebSearchSummary',
            },
        ),
    ]
