# Generated by Django 6.0.3 on 2026-06-05 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stage', '0017_websearchidee_websearchsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('nb_mots', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('livre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='postface', to='Stage.livre')),
            ],
            options={
                'db_table': 'Postface',
            },
        ),
        migrations.CreateModel(
            name='Preface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('nb_mots', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('livre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preface', to='Stage.livre')),
            ],
            options={
                'db_table': 'Preface',
            },
        ),
    ]
