# Generated by Django 6.0.3 on 2026-06-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stage', '0018_postface_preface'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postface',
            name='livre',
        ),
        migrations.RemoveField(
            model_name='preface',
            name='livre',
        ),
        migrations.AddField(
            model_name='postface',
            name='livre_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preface',
            name='livre_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
