# Generated by Django 6.0.3 on 2026-06-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stage', '0019_remove_postface_livre_remove_preface_livre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapes',
            name='postface',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='etapes',
            name='preface',
            field=models.BooleanField(default=False),
        ),
    ]
